### PR TITLE
#28 - Refactor User module

### PR DESCRIPTION
**Pull request by AshenNagamaki**

### CODE REVIEW

**Comment by AshenNagamaki** [comment]
> Not tested yet.

Checked, passed all tests.

**Review by IINamelessII — APPROVED** [review]
LGTM

**Review by IINamelessII — DISMISSED** [review]
Still LGTM

**Comment by yugisu** [comment]
Same as Oleg, LGTM

**Review by yugisu — APPROVED** [review]

**Review by RedBullDogE — APPROVED** [review]

**Pull request merged**
